countries_w_frontiers = {"Afghanistan": ["Chine", "Iran", "Ouzbekistan", "Pakistan", "Tadjikistan", "Turkmenistan"],
    "Afrique du Sud": ["Botswana", "Lesotho", "Mozambique", "Namibie", "Eswatini", "Zimbabwe"],
    "Albanie": ["Grece", "Macedoine du Nord", "Montenegro", "Kosovo"],
    "Algerie": ["Libye", "Mali", "Maroc", "Mauritanie", "Niger", "Tunisie"],
    "Allemagne": ["Autriche", "Belgique", "Danemark", "France", "Luxembourg", "Pays-Bas", "Pologne", "Suisse", "Tchequie"],
    "Andorre": ["Espagne", "France"],
    "Angola": ["Namibie", "Republique democratique du Congo", "Republique du Congo", "Zambie"],
    "arabie saoudite": ["eau", "Irak", "Jordanie", "Koweit", "Oman", "Qatar", "Yemen"],
    "Argentine": ["Bolivie", "Bresil", "Chili", "Paraguay", "Uruguay"],
    "Armenie": ["Azerbaidjan", "Georgie", "Iran", "Turquie"],
    "Autriche": ["Allemagne", "Hongrie", "Italie", "Liechtenstein", "Slovaquie", "Slovenie", "Suisse", "Tchequie"],
    "Azerbaidjan": ["Armenie", "Georgie", "Iran", "Russie", "Turquie"],
    "Bangladesh": ["Inde", "Myanmar"],
    "Belgique": ["Allemagne", "France", "Luxembourg", "Pays-Bas"],
    "Belize": ["Guatemala", "Mexique"],
    "Bhoutan": ["Chine", "Inde"],
    "Bielorussie": ["Lettonie", "Lituanie", "Pologne", "Russie", "Ukraine"],
    "Bolivie": ["Argentine", "Bresil", "Chili", "Paraguay", "Perou"],
    "Bosnie": ["Croatie", "Montenegro", "Serbie"],
    "Botswana": ["Afrique du Sud", "Namibie", "Zambie", "Zimbabwe"],
    "Brunei": ["Malaisie"],
    "Bresil": ["Argentine", "Bolivie", "Colombie", "Guyana", "Paraguay", "Perou", "Suriname", "Uruguay", "Venezuela"],
    "Bulgarie": ["Grece", "Macedoine du Nord", "Roumanie", "Serbie", "Turquie"],
    "Burkina Faso": ["Benin", "Cote d'Ivoire", "Ghana", "Mali", "Niger", "Togo"],
    "Burundi": ["Republique democratique du Congo", "Rwanda", "Tanzanie"],
    "Benin": ["Burkina Faso", "Niger", "Nigeria", "Togo"],
    "Cambodge": ["Laos", "Thailande", "Viêt Nam"],
    "Cameroun": ["Gabon", "Guinee equatoriale", "Nigeria", "Republique Centrafricaine", "Republique du Congo", "Tchad"],
    "Canada": ["Etats-Unis"],
    "Chili": ["Argentine", "Bolivie", "Perou"],
    "Chine": ["Afghanistan", "Bhoutan", "Inde", "Kazakhstan", "Kirghizistan", "Laos", "Mongolie", "Myanmar", "Nepal", "Pakistan", "Russie", "Tadjikistan", "Viêt Nam", "Coree du Nord"],
    "Colombie": ["Bresil", "equateur", "Panama", "Perou", "Venezuela"],
    "Coree du Nord": ["Chine", "Coree du Sud", "Russie"],
    "Coree du Sud": ["Coree du Nord"],
    "Costa Rica": ["Nicaragua", "Panama"],
    "Croatie": ["Bosnie", "Hongrie", "Montenegro", "Serbie", "Slovenie"],
    "Cote d'Ivoire": ["Burkina Faso", "Ghana", "Guinee", "Liberia", "Mali"],
    "Danemark": ["Allemagne"],
    "Djibouti": ["erythree", "ethiopie", "Somalie"],
    "egypte": ["Israël", "Libye", "Soudan"],
    "eau": ["arabie saoudite", "Oman"],
    "equateur": ["Colombie", "Perou"],
    "erythree": ["Djibouti", "ethiopie", "Soudan"],
    "Espagne": ["Andorre", "France", "Portugal", "Royaume-Uni"],
    "Estonie": ["Lettonie", "Russie"],
    "Eswatini": ["Afrique du Sud", "Mozambique"],
    "Etats-Unis": ["Canada", "Mexique"],
    "ethiopie": ["Djibouti", "erythree", "Kenya", "Somalie", "Soudan", "Soudan du Sud"],
    "Finlande": ["Norvege", "Russie", "Suede"],
    "France": ["Allemagne", "Andorre", "Belgique", "Espagne", "Italie", "Luxembourg", "Monaco", "Suisse"],
    "Gabon": ["Cameroun", "Guinee equatoriale", "Republique du Congo"],
    "Gambie": ["Senegal"],
    "Ghana": ["Burkina Faso", "Cote d'Ivoire", "Togo"],
    "Grece": ["Albanie", "Bulgarie", "Macedoine du Nord", "Turquie"],
    "Guatemala": ["Belize", "Honduras", "Mexique", "Salvador"],
    "Guinee": ["Cote d'Ivoire", "Guinee-Bissau", "Liberia", "Mali", "Senegal", "Sierra Leone"],
    "Guinee equatoriale": ["Cameroun", "Gabon"],
    "Guinee-Bissau": ["Guinee", "Senegal"],
    "Guyana": ["Bresil", "Suriname", "Venezuela"],
    "Georgie": ["Armenie", "Azerbaidjan", "Russie", "Turquie"],
    "Haiti": ["Republique dominicaine"],
    "Honduras": ["Guatemala", "Nicaragua", "Salvador"],
    "Hongrie": ["Autriche", "Croatie", "Roumanie", "Serbie", "Slovaquie", "Slovenie", "Ukraine"],
    "Inde": ["Bangladesh", "Bhoutan", "Chine", "Myanmar", "Nepal", "Pakistan"],
    "Indonesie": ["Malaisie", "Papouasie-Nouvelle-Guinee", "Timor-Leste"],
    "Irak": ["arabie saoudite", "Iran", "Jordanie", "Koweit", "Syrie", "Turquie"],
    "Iran": ["Afghanistan", "Armenie", "Azerbaidjan", "Irak", "Pakistan", "Turkmenistan", "Turquie"],
    "Irlande": ["Royaume-Uni"],
    "Israël": ["egypte", "Jordanie", "Liban", "Syrie"],
    "Italie": ["Autriche", "France", "Saint-Marin", "Slovenie", "Suisse", "Vatican"],
    "Jordanie": ["arabie saoudite", "Irak", "Israël", "Syrie"],
    "Kazakhstan": ["Chine", "Kirghizistan", "Ouzbekistan", "Russie", "Turkmenistan"],
    "Kenya": ["ethiopie", "Ouganda", "Somalie", "Soudan du Sud", "Tanzanie"],
    "Kirghizistan": ["Chine", "Kazakhstan", "Ouzbekistan", "Tadjikistan"],
    "Kosovo": ["Albanie", "Macedoine du Nord", "Montenegro", "Serbie"],
    "Koweit": ["arabie saoudite", "Irak"],
    "Laos": ["Cambodge", "Chine", "Myanmar", "Thailande", "Viêt Nam"],
    "Lesotho": ["Afrique du Sud"],
    "Lettonie": ["Bielorussie", "Estonie", "Lituanie", "Russie"],
    "Liban": ["Israël", "Syrie"],
    "Liberia": ["Cote d'Ivoire", "Guinee", "Sierra Leone"],
    "Libye": ["Algerie", "egypte", "Niger", "Soudan", "Tchad", "Tunisie"],
    "Liechtenstein": ["Autriche", "Suisse"],
    "Lituanie": ["Bielorussie", "Lettonie", "Pologne", "Russie"],
    "Luxembourg": ["Allemagne", "Belgique", "France"],
    "Macedoine du Nord": ["Albanie", "Bulgarie", "Grece", "Kosovo", "Serbie"],
    "Malaisie": ["Brunei", "Indonesie", "Thailande"],
    "Malawi": ["Mozambique", "Tanzanie", "Zambie"],
    "Mali": ["Algerie", "Burkina Faso", "Cote d'Ivoire", "Guinee", "Mauritanie", "Niger", "Senegal"],
    "Maroc": ["Algerie", "Espagne", "Mauritanie"],
    "Mauritanie": ["Algerie", "Mali", "Maroc", "Senegal"],
    "Mexique": ["Belize", "Etats-Unis", "Guatemala"],
    "Moldavie": ["Roumanie", "Ukraine"],
    "Monaco": ["France"],
    "Mongolie": ["Chine", "Russie"],
    "Montenegro": ["Albanie", "Bosnie", "Croatie", "Kosovo", "Serbie"],
    "Mozambique": ["Afrique du Sud", "Eswatini", "Malawi", "Tanzanie", "Zambie", "Zimbabwe"],
    "Myanmar": ["Bangladesh", "Chine", "Inde", "Laos", "Thailande"],
    "Namibie": ["Afrique du Sud", "Angola", "Botswana", "Zambie"],
    "Nicaragua": ["Costa Rica", "Honduras"],
    "Niger": ["Algerie", "Benin", "Burkina Faso", "Libye", "Mali", "Nigeria", "Tchad"],
    "Nigeria": ["Benin", "Cameroun", "Niger", "Tchad"],
    "Norvege": ["Finlande", "Russie", "Suede"],
    "Nepal": ["Chine", "Inde"],
    "Oman": ["arabie saoudite", "eau", "Yemen"],
    "Ouganda": ["Kenya", "Republique democratique du Congo", "Rwanda", "Soudan du Sud", "Tanzanie"],
    "Ouzbekistan": ["Afghanistan", "Kazakhstan", "Kirghizistan", "Tadjikistan", "Turkmenistan"],
    "Pakistan": ["Afghanistan", "Chine", "Inde", "Iran"],
    "Panama": ["Colombie", "Costa Rica"],
    "Papouasie-Nouvelle-Guinee": ["Indonesie"],
    "Paraguay": ["Argentine", "Bolivie", "Bresil"],
    "Pays-Bas": ["Allemagne", "Belgique"],
    "Pologne": ["Allemagne", "Bielorussie", "Lituanie", "Russie", "Slovaquie", "Tchequie", "Ukraine"],
    "Portugal": ["Espagne"],
    "Perou": ["Bolivie", "Bresil", "Chili", "Colombie", "equateur"],
    "Qatar": ["arabie saoudite"],
    "Roumanie": ["Bulgarie", "Hongrie", "Moldavie", "Serbie", "Ukraine"],
    "Royaume-Uni": ["Espagne", "Irlande"],
    "Russie": ["Azerbaidjan", "Bielorussie", "Chine", "Coree du Nord", "Estonie", "Finlande", "Georgie", "Kazakhstan", "Lettonie", "Lituanie", "Mongolie", "Norvege", "Pologne", "Ukraine"],
    "Rwanda": ["Burundi", "Ouganda", "Republique democratique du Congo", "Tanzanie"],
    "Republique Centrafricaine": ["Cameroun", "Republique democratique du Congo", "Republique du Congo", "Soudan du Sud", "Tchad"],
    "Republique dominicaine": ["Haiti"],
    "Republique du Congo": ["Angola", "Cameroun", "Gabon", "Republique Centrafricaine", "Republique democratique du Congo"],
    "Republique democratique du Congo": ["Angola", "Burundi", "Ouganda", "Republique Centrafricaine", "Republique du Congo", "Rwanda", "Soudan du Sud", "Tanzanie", "Zambie"],
    "Saint-Marin": ["Italie"],
    "Salvador": ["Guatemala", "Honduras"],
    "Serbie": ["Bosnie", "Bulgarie", "Croatie", "Hongrie", "Kosovo", "Macedoine du Nord", "Montenegro", "Roumanie"],
    "Sierra Leone": ["Guinee", "Liberia"],
    "Slovaquie": ["Autriche", "Hongrie", "Pologne", "Tchequie", "Ukraine"],
    "Slovenie": ["Autriche", "Croatie", "Hongrie", "Italie"],
    "Somalie": ["Djibouti", "ethiopie", "Kenya"],
    "Soudan": ["egypte", "erythree", "ethiopie", "Libye", "Republique Centrafricaine", "Soudan du Sud", "Tchad"],
    "Soudan du Sud": ["ethiopie", "Kenya", "Ouganda", "Republique Centrafricaine", "Republique democratique du Congo", "Soudan"],
    "Sri Lanka": [],
    "Suisse": ["Allemagne", "Autriche", "France", "Italie", "Liechtenstein"],
    "Suriname": ["Bresil", "Guyana"],
    "Suede": ["Finlande", "Norvege"],
    "Syrie": ["Irak", "Israël", "Jordanie", "Liban", "Turquie"],
    "Senegal": ["Gambie", "Guinee", "Guinee-Bissau", "Mali", "Mauritanie"],
    "Tadjikistan": ["Afghanistan", "Chine", "Kirghizistan", "Ouzbekistan"],
    "Tanzanie": ["Burundi", "Kenya", "Malawi", "Mozambique", "Ouganda", "Republique democratique du Congo", "Rwanda", "Zambie"],
    "Tchad": ["Cameroun", "Libye", "Niger", "Nigeria", "Republique Centrafricaine", "Soudan"],
    "Tchequie": ["Allemagne", "Autriche", "Pologne", "Slovaquie"],
    "Thailande": ["Cambodge", "Laos", "Malaisie", "Myanmar"],
    "Timor-Leste": ["Indonesie"],
    "Togo": ["Benin", "Burkina Faso", "Ghana"],
    "Tunisie": ["Algerie", "Libye"],
    "Turkmenistan": ["Afghanistan", "Iran", "Kazakhstan", "Ouzbekistan"],
    "Turquie": ["Armenie", "Azerbaidjan", "Bulgarie", "Georgie", "Grece", "Iran", "Irak", "Syrie"],
    "Ukraine": ["Bielorussie", "Hongrie", "Moldavie", "Pologne", "Roumanie", "Russie", "Slovaquie"],
    "Uruguay": ["Argentine", "Bresil"],
    "Vatican": ["Italie"],
    "Venezuela": ["Bresil", "Colombie", "Guyana"],
    "Viêt Nam": ["Cambodge", "Chine", "Laos"],
    "Yemen": ["arabie saoudite", "Oman"],
    "Zambie": ["Angola", "Botswana", "Malawi", "Mozambique", "Namibie", "Republique democratique du Congo", "Tanzanie", "Zimbabwe"],
    "Zimbabwe": ["Afrique du Sud", "Botswana", "Mozambique", "Zambie"]
}